name: Build a Greengrass image

on:
  workflow_call:
    inputs:
      greengrass_docker_ref: { required: true,  type: string }   # e.g. main, v1.64.0
      greengrass_nucleus_version: { required: true,  type: string }   # e.g. 2.14.3

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/greengrass-nucleus

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: aws-greengrass/aws-greengrass-docker
          ref:  "${{ inputs.greengrass_docker_ref }}"
          path: docker-src

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.greengrass_nucleus_version }}-docker${{ inputs.greengrass_docker_ref }}
          labels: |
            org.opencontainers.image.title=AWS Greengrass Nucleus
            org.opencontainers.image.version=${{ inputs.greengrass_nucleus_version }}-docker${{ inputs.greengrass_docker_ref }}
            org.opencontainers.image.description=Image built from aws-greengrass-docker v${{ inputs.greengrass_docker_ref }} for Greengrass Nucleus ${{ inputs.greengrass_nucleus_version }}
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: docker-src
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GREENGRASS_RELEASE_VERSION=${{ inputs.greengrass_nucleus_version }}
          tags:   ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
