name: Build latest Greengrass versions daily

on:
  schedule:       # once per day
    - cron: '30 3 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      greengrass_nucleus_version_matrix: ${{ steps.set.outputs.greengrass_nucleus_version_matrix }}
      greengrass_docker_ref:             ${{ steps.set.outputs.greengrass_docker_ref }}
    steps:
      - id: set
        run: |
          set -euo pipefail

          # latest working version for aws-greengrass-docker
          greengrass_docker_ref=f745fdec
          echo "Greengrass docker ref: ${greengrass_docker_ref}"

          # latest two minors from aws-greengrass-nucleus
          greengrass_nucleus_versions=$(curl -fsSL https://api.github.com/repos/aws-greengrass/aws-greengrass-nucleus/releases | 
                         jq -r '.[] | select(.prerelease == false) | .tag_name' | 
                         sed 's/^v//' | 
                         sort -rV)
          latest_minors=$(echo "$greengrass_nucleus_versions" | awk -F. '{print $1"."$2}' |  sort -rV | uniq | head -2)
          latest=()
          while IFS= read -r version; do
            for minor in $latest_minors; do
              if [[ "${version%.*}" == "$minor" ]]; then
                latest+=("$version")
                break
              fi
            done
          done <<< "$greengrass_nucleus_versions"
          greengrass_nucleus_version_matrix="$(printf '%s\n' "${latest[@]}" | jq -R . | jq -cs '{version: .}')"
          echo "Greengrass nucleus versions matrix: ${greengrass_nucleus_version_matrix}"

          echo "greengrass_docker_ref=${greengrass_docker_ref}" >>"$GITHUB_OUTPUT"
          echo "greengrass_nucleus_version_matrix=${greengrass_nucleus_version_matrix}" >>"$GITHUB_OUTPUT"

  build:
    needs: discover
    strategy:
      matrix: ${{ fromJson(needs.discover.outputs.greengrass_nucleus_version_matrix) }}
      fail-fast: false
    uses: ./.github/workflows/build-image.yml
    with:
      greengrass_docker_ref:      ${{ needs.discover.outputs.greengrass_docker_ref }}
      greengrass_nucleus_version: ${{ matrix.version }}
